/**
 * Room lifecycle engine, per docs/DESIGN.md §5 (screens) and §6 (data model).
 *
 * Pure `(room, ...action, now) => Room | RoomEngineResult<Room>` — no I/O, no
 * `Date.now()`. Identity (`seatId`/`publicId`) is generated by the caller
 * (the Durable Object, per T-09's "join handshake issues seatId +
 * resumeToken") and passed in, so every outcome here is deterministic.
 *
 * `canStartGame` is a pure predicate over team composition, for T-17's future
 * team-select-validated `start_game`. `startOneVOneGame` (T-14) is a
 * separate, narrower transition to `IN_GAME` for the 1v1 case only — see its
 * own doc comment for why it doesn't reuse `canStartGame`.
 */
import { startGame as buildInitialGameState } from './gameEngine.js';
import { DEFAULT_TIME_CONTROL } from './timeControls.js';
import type { ErrorCode, Room, RoomCode, RoomSettings, Seat, SeatId, Spectator, Team } from './types.js';

export const MAX_SEATS = 4;
export const MAX_SPECTATORS = 20;
export const MAX_TEAM_SIZE = 2;

export type RoomEngineResult<T> = { ok: true; value: T } | { ok: false; code: ErrorCode };

function ok<T>(value: T): RoomEngineResult<T> {
  return { ok: true, value };
}

function fail<T>(code: ErrorCode): RoomEngineResult<T> {
  return { ok: false, code };
}

export const DEFAULT_ROOM_SETTINGS: RoomSettings = {
  timeControl: DEFAULT_TIME_CONTROL,
  randomizeColors: false,
  allowSpectators: true,
  disconnectGraceMs: 90_000,
};

export interface RoomJoiner {
  seatId: SeatId;
  publicId: string;
  username: string;
}

export function createRoom(
  code: RoomCode,
  host: RoomJoiner,
  now: number,
  settings: RoomSettings = DEFAULT_ROOM_SETTINGS,
): Room {
  const hostSeat: Seat = {
    seatId: host.seatId,
    publicId: host.publicId,
    username: host.username,
    team: null,
    isHost: true,
    connected: true,
    lastSeenAt: now,
    ready: false,
  };
  return {
    code,
    createdAt: now,
    phase: 'LOBBY',
    seats: [hostSeat],
    spectators: [],
    chat: [],
    settings,
    game: null,
  };
}

export type JoinRoomOutcome = { role: 'seat' | 'spectator'; room: Room };

/**
 * A 5th+ joiner, or anyone joining while `phase === 'IN_GAME'`, spectates
 * regardless of how many seats are occupied (§5.7).
 */
export function joinRoom(room: Room, joiner: RoomJoiner, now: number): RoomEngineResult<JoinRoomOutcome> {
  const mustSpectate = room.phase === 'IN_GAME' || room.seats.length >= MAX_SEATS;

  if (!mustSpectate) {
    const seat: Seat = {
      seatId: joiner.seatId,
      publicId: joiner.publicId,
      username: joiner.username,
      team: null,
      isHost: false,
      connected: true,
      lastSeenAt: now,
      ready: false,
    };
    return ok({ role: 'seat', room: { ...room, seats: [...room.seats, seat] } });
  }

  if (!room.settings.allowSpectators) {
    return fail('SPECTATORS_DISABLED');
  }
  if (room.spectators.length >= MAX_SPECTATORS) {
    return fail('ROOM_FULL');
  }

  const spectator: Spectator = {
    seatId: joiner.seatId,
    publicId: joiner.publicId,
    username: joiner.username,
    connected: true,
    joinedAt: now,
  };
  return ok({ role: 'spectator', room: { ...room, spectators: [...room.spectators, spectator] } });
}

/**
 * Removes a seat or spectator. A no-op if `seatId` isn't present — leaving
 * is idempotent so a duplicate or racing call can't fail. If the departing
 * seat was host and another seat remains, the earliest-joined remaining seat
 * becomes host so host-only actions stay available.
 */
export function leaveRoom(room: Room, seatId: SeatId): Room {
  const seatIndex = room.seats.findIndex((s) => s.seatId === seatId);
  if (seatIndex !== -1) {
    const leaving = room.seats[seatIndex]!;
    const remaining = room.seats.filter((_, i) => i !== seatIndex);
    const needsNewHost = leaving.isHost && remaining.length > 0;
    const seats = needsNewHost
      ? remaining.map((s, i) => (i === 0 ? { ...s, isHost: true } : s))
      : remaining;
    return { ...room, seats };
  }

  const spectators = room.spectators.filter((s) => s.seatId !== seatId);
  return spectators.length === room.spectators.length ? room : { ...room, spectators };
}

/** `team: null` unassigns. Joining a team already at `MAX_TEAM_SIZE` is rejected. */
export function setTeam(room: Room, seatId: SeatId, team: Team | null, now: number): RoomEngineResult<Room> {
  const seat = room.seats.find((s) => s.seatId === seatId);
  if (!seat) return fail('SEAT_NOT_FOUND');

  if (team !== null && seat.team !== team) {
    const teamSize = room.seats.filter((s) => s.team === team).length;
    if (teamSize >= MAX_TEAM_SIZE) return fail('TEAM_FULL');
  }

  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, team, lastSeenAt: now } : s));
  return ok({ ...room, seats });
}

export function setReady(room: Room, seatId: SeatId, ready: boolean, now: number): RoomEngineResult<Room> {
  const seat = room.seats.find((s) => s.seatId === seatId);
  if (!seat) return fail('SEAT_NOT_FOUND');

  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, ready, lastSeenAt: now } : s));
  return ok({ ...room, seats });
}

/** Host-only, full replacement of `settings` (§7 `update_settings`). */
export function updateSettings(room: Room, actorSeatId: SeatId, settings: RoomSettings): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');

  return ok({ ...room, settings });
}

/**
 * Host-only, and only outside `IN_GAME` (§5.7 "Mid-game promotion is not
 * allowed"). Moves the spectator into `team`, keeping their existing
 * `seatId` since it's the same connection.
 */
export function promoteSpectator(
  room: Room,
  actorSeatId: SeatId,
  targetPublicId: string,
  team: Team,
  now: number,
): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase === 'IN_GAME') return fail('INVALID_PHASE');

  const spectator = room.spectators.find((s) => s.publicId === targetPublicId);
  if (!spectator) return fail('SPECTATOR_NOT_FOUND');

  if (room.seats.length >= MAX_SEATS) return fail('ROOM_FULL');
  const teamSize = room.seats.filter((s) => s.team === team).length;
  if (teamSize >= MAX_TEAM_SIZE) return fail('TEAM_FULL');

  const seat: Seat = {
    seatId: spectator.seatId,
    publicId: spectator.publicId,
    username: spectator.username,
    team,
    isHost: false,
    connected: spectator.connected,
    lastSeenAt: now,
    ready: false,
  };

  return ok({
    ...room,
    seats: [...room.seats, seat],
    spectators: room.spectators.filter((s) => s.publicId !== targetPublicId),
  });
}

/**
 * Marks a seat or spectator's socket as (dis)connected, e.g. on
 * `webSocketClose`/reconnect in the Durable Object (T-09). A no-op for an
 * unknown `seatId`, matching `leaveRoom`'s idempotent shape — the caller may
 * race a close event against a room that's already moved on.
 */
export function setConnected(room: Room, seatId: SeatId, connected: boolean, now: number): Room {
  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, connected, lastSeenAt: now } : s));
  const spectators = room.spectators.map((s) => (s.seatId === seatId ? { ...s, connected } : s));
  return { ...room, seats, spectators };
}

/**
 * True only for the four team compositions §5.4 allows to start:
 * `(2,2) (2,1) (1,2) (1,1)`. Neither team may be empty or exceed
 * `MAX_TEAM_SIZE`; unassigned seats simply don't count toward either side.
 */
export function canStartGame(seats: Seat[]): boolean {
  const white = seats.filter((s) => s.team === 'WHITE').length;
  const black = seats.filter((s) => s.team === 'BLACK').length;
  return white >= 1 && white <= MAX_TEAM_SIZE && black >= 1 && black <= MAX_TEAM_SIZE;
}

/**
 * Host-only `start_game` for the 1v1 case (T-14 — "Networked 1v1", the
 * milestone `docs/DESIGN.md` §13 deliberately sequences before Team Select).
 * No FIFA screen exists yet for players to pick sides, so with exactly two
 * seats the join order decides colors: the host is WHITE, the other seat
 * BLACK — matching §4.2's "Team 1 is White" default. `settings.randomizeColors`
 * isn't applied here: `update_settings` isn't wired server-side until T-17
 * (see TASKS.md's T-09 Finding), so it can never actually be `true` yet.
 *
 * `canStartGame`'s four-composition predicate deliberately isn't reused here
 * — every seat's `team` is still `null` at this point (nothing assigns one
 * before this task), and 2v2/2v1 compositions have no propose/accept
 * mechanism to actually play with (T-18). T-17 replaces this whole function
 * with the real team-select-validated transition.
 *
 * No `now` parameter: nothing here is time-derived — `game.clock.turnStartedAt`
 * stays `null` until White's first commit (§4.6), same reasoning T-13 used to
 * drop `now` from `gameEngine.startGame`.
 */
export function startOneVOneGame(room: Room, actorSeatId: SeatId): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase !== 'LOBBY') return fail('INVALID_PHASE');
  if (room.seats.length !== 2) return fail('TEAM_SIZE_INVALID');

  const [white, black] = room.seats;
  const seats: Seat[] = [
    { ...white!, team: 'WHITE' },
    { ...black!, team: 'BLACK' },
  ];

  return ok({
    ...room,
    phase: 'IN_GAME',
    seats,
    game: buildInitialGameState(room.settings.timeControl),
  });
}
