/**
 * Room lifecycle engine, per docs/DESIGN.md §5 (screens) and §6 (data model).
 *
 * Pure `(room, ...action, now) => Room | RoomEngineResult<Room>` — no I/O, no
 * `Date.now()`. Identity (`seatId`/`publicId`) is generated by the caller
 * (the Durable Object, per T-09's "join handshake issues seatId +
 * resumeToken") and passed in, so every outcome here is deterministic.
 *
 * `canStartGame` is a pure predicate over team composition, used by
 * `startGameFromTeamSelect` (T-17) to validate the real, team-select-gated
 * `IN_GAME` transition — see its own doc comment.
 */
import { startGame as buildInitialGameState } from './gameEngine.js';
import { DEFAULT_TIME_CONTROL } from './timeControls.js';
import type {
  ChatChannel,
  ChatMessage,
  ErrorCode,
  Room,
  RoomCode,
  RoomSettings,
  Seat,
  SeatId,
  Spectator,
  Team,
} from './types.js';

export const MAX_SEATS = 4;
export const MAX_SPECTATORS = 20;
export const MAX_TEAM_SIZE = 2;

/** §5.8: "last 100 messages are held ... replayed on join/reconnect." */
export const CHAT_HISTORY_LIMIT = 100;
/** §5.8: "rate-limited to 5 messages per 10 seconds per seat." */
export const CHAT_RATE_LIMIT_COUNT = 5;
export const CHAT_RATE_LIMIT_WINDOW_MS = 10_000;

export type RoomEngineResult<T> = { ok: true; value: T } | { ok: false; code: ErrorCode };

function ok<T>(value: T): RoomEngineResult<T> {
  return { ok: true, value };
}

function fail<T>(code: ErrorCode): RoomEngineResult<T> {
  return { ok: false, code };
}

export const DEFAULT_ROOM_SETTINGS: RoomSettings = {
  timeControl: DEFAULT_TIME_CONTROL,
  randomizeColors: false,
  allowSpectators: true,
  disconnectGraceMs: 90_000,
};

export interface RoomJoiner {
  seatId: SeatId;
  publicId: string;
  username: string;
}

export function createRoom(
  code: RoomCode,
  host: RoomJoiner,
  now: number,
  settings: RoomSettings = DEFAULT_ROOM_SETTINGS,
): Room {
  const hostSeat: Seat = {
    seatId: host.seatId,
    publicId: host.publicId,
    username: host.username,
    team: null,
    isHost: true,
    connected: true,
    lastSeenAt: now,
    ready: false,
  };
  return {
    code,
    createdAt: now,
    phase: 'LOBBY',
    seats: [hostSeat],
    spectators: [],
    chat: [],
    settings,
    game: null,
  };
}

export type JoinRoomOutcome = { role: 'seat' | 'spectator'; room: Room };

/**
 * A 5th+ joiner, or anyone joining while `phase === 'IN_GAME'`, spectates
 * regardless of how many seats are occupied (§5.7).
 */
export function joinRoom(room: Room, joiner: RoomJoiner, now: number): RoomEngineResult<JoinRoomOutcome> {
  const mustSpectate = room.phase === 'IN_GAME' || room.seats.length >= MAX_SEATS;

  if (!mustSpectate) {
    const seat: Seat = {
      seatId: joiner.seatId,
      publicId: joiner.publicId,
      username: joiner.username,
      team: null,
      isHost: false,
      connected: true,
      lastSeenAt: now,
      ready: false,
    };
    return ok({ role: 'seat', room: { ...room, seats: [...room.seats, seat] } });
  }

  if (!room.settings.allowSpectators) {
    return fail('SPECTATORS_DISABLED');
  }
  if (room.spectators.length >= MAX_SPECTATORS) {
    return fail('ROOM_FULL');
  }

  const spectator: Spectator = {
    seatId: joiner.seatId,
    publicId: joiner.publicId,
    username: joiner.username,
    connected: true,
    joinedAt: now,
  };
  return ok({ role: 'spectator', room: { ...room, spectators: [...room.spectators, spectator] } });
}

/**
 * Removes a seat or spectator. A no-op if `seatId` isn't present — leaving
 * is idempotent so a duplicate or racing call can't fail. If the departing
 * seat was host and another seat remains, the earliest-joined remaining seat
 * becomes host so host-only actions stay available.
 */
export function leaveRoom(room: Room, seatId: SeatId): Room {
  const seatIndex = room.seats.findIndex((s) => s.seatId === seatId);
  if (seatIndex !== -1) {
    const leaving = room.seats[seatIndex]!;
    const remaining = room.seats.filter((_, i) => i !== seatIndex);
    const needsNewHost = leaving.isHost && remaining.length > 0;
    const seats = needsNewHost
      ? remaining.map((s, i) => (i === 0 ? { ...s, isHost: true } : s))
      : remaining;
    return { ...room, seats };
  }

  const spectators = room.spectators.filter((s) => s.seatId !== seatId);
  return spectators.length === room.spectators.length ? room : { ...room, spectators };
}

/**
 * `team: null` unassigns. Joining a team already at `MAX_TEAM_SIZE` is
 * rejected. Blocked outside `LOBBY`/`TEAM_SELECT`: `RoomDO.handlePropose`
 * (T-14) trusts `seat.team` fresh off `room.seats` on every `propose` to
 * decide who's moving for which side, so an unguarded mid-game `set_team`
 * would let a player hop onto whichever side is on move and commit moves
 * that aren't theirs — exactly the class of bug CLAUDE.md rule 2 exists to
 * prevent, invisible in manual testing until someone tries it maliciously.
 */
export function setTeam(room: Room, seatId: SeatId, team: Team | null, now: number): RoomEngineResult<Room> {
  const seat = room.seats.find((s) => s.seatId === seatId);
  if (!seat) return fail('SEAT_NOT_FOUND');
  if (room.phase === 'IN_GAME' || room.phase === 'FINISHED') return fail('INVALID_PHASE');

  if (team !== null && seat.team !== team) {
    const teamSize = room.seats.filter((s) => s.team === team).length;
    if (teamSize >= MAX_TEAM_SIZE) return fail('TEAM_FULL');
  }

  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, team, lastSeenAt: now } : s));
  return ok({ ...room, seats });
}

/** Blocked outside `LOBBY`/`TEAM_SELECT` — "ready" has no meaning once a game is already running. */
export function setReady(room: Room, seatId: SeatId, ready: boolean, now: number): RoomEngineResult<Room> {
  const seat = room.seats.find((s) => s.seatId === seatId);
  if (!seat) return fail('SEAT_NOT_FOUND');
  if (room.phase === 'IN_GAME' || room.phase === 'FINISHED') return fail('INVALID_PHASE');

  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, ready, lastSeenAt: now } : s));
  return ok({ ...room, seats });
}

/** Host-only, full replacement of `settings` (§7 `update_settings`). */
export function updateSettings(room: Room, actorSeatId: SeatId, settings: RoomSettings): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');

  return ok({ ...room, settings });
}

/**
 * Host-only, and only outside `IN_GAME` (§5.7 "Mid-game promotion is not
 * allowed"). Moves the spectator into `team`, keeping their existing
 * `seatId` since it's the same connection.
 */
export function promoteSpectator(
  room: Room,
  actorSeatId: SeatId,
  targetPublicId: string,
  team: Team,
  now: number,
): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase === 'IN_GAME') return fail('INVALID_PHASE');

  const spectator = room.spectators.find((s) => s.publicId === targetPublicId);
  if (!spectator) return fail('SPECTATOR_NOT_FOUND');

  if (room.seats.length >= MAX_SEATS) return fail('ROOM_FULL');
  const teamSize = room.seats.filter((s) => s.team === team).length;
  if (teamSize >= MAX_TEAM_SIZE) return fail('TEAM_FULL');

  const seat: Seat = {
    seatId: spectator.seatId,
    publicId: spectator.publicId,
    username: spectator.username,
    team,
    isHost: false,
    connected: spectator.connected,
    lastSeenAt: now,
    ready: false,
  };

  return ok({
    ...room,
    seats: [...room.seats, seat],
    spectators: room.spectators.filter((s) => s.publicId !== targetPublicId),
  });
}

/**
 * Marks a seat or spectator's socket as (dis)connected, e.g. on
 * `webSocketClose`/reconnect in the Durable Object (T-09). A no-op for an
 * unknown `seatId`, matching `leaveRoom`'s idempotent shape — the caller may
 * race a close event against a room that's already moved on.
 */
export function setConnected(room: Room, seatId: SeatId, connected: boolean, now: number): Room {
  const seats = room.seats.map((s) => (s.seatId === seatId ? { ...s, connected, lastSeenAt: now } : s));
  const spectators = room.spectators.map((s) => (s.seatId === seatId ? { ...s, connected } : s));
  return { ...room, seats, spectators };
}

/**
 * True only for the four team compositions §5.4 allows to start:
 * `(2,2) (2,1) (1,2) (1,1)`. Neither team may be empty or exceed
 * `MAX_TEAM_SIZE`; unassigned seats simply don't count toward either side.
 *
 * Takes anything with a `team`, not specifically `Seat[]` — the client's
 * Team Select screen (T-17) only ever has `PublicSeat[]` (`seatId` stripped
 * by `redactFor()`) in hand, and this predicate never needed `seatId`.
 */
export function canStartGame(seats: ReadonlyArray<{ team: Team | null }>): boolean {
  const white = seats.filter((s) => s.team === 'WHITE').length;
  const black = seats.filter((s) => s.team === 'BLACK').length;
  return white >= 1 && white <= MAX_TEAM_SIZE && black >= 1 && black <= MAX_TEAM_SIZE;
}

/**
 * How many of `team`'s seats currently count toward requiring confirmation
 * (§4.4 solo teams; §9 "a disconnected teammate ... team is temporarily
 * treated as solo"). Only *connected* seats count, so a 2-player team with
 * one teammate disconnected reads identically to a genuinely-solo 2v1 seat —
 * no special-casing needed at the call site (`gameEngine.requiresConfirmation`).
 */
export function connectedTeamSize(
  seats: ReadonlyArray<{ team: Team | null; connected: boolean }>,
  team: Team,
): number {
  return seats.filter((s) => s.team === team && s.connected).length;
}

/**
 * Host-only `LOBBY` -> `TEAM_SELECT` transition (T-17, resolving the
 * §5.3/§5.4 screen-map ambiguity logged in TASKS.md's Findings): the
 * Lobby's existing Start button, gated on player count alone since T-10,
 * now takes the room to the FIFA screen instead of directly into a game.
 * Same `seats.length >= 2` gate T-10's own Lobby e2e spec already
 * established ("start is disabled with one player and enabled with two")
 * — nothing here tightens it, since no seat has a team yet at this point.
 */
export function advanceToTeamSelect(room: Room, actorSeatId: SeatId): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase !== 'LOBBY') return fail('INVALID_PHASE');
  if (room.seats.length < 2) return fail('TEAM_SIZE_INVALID');

  return ok({ ...room, phase: 'TEAM_SELECT' });
}

/**
 * Host-only `TEAM_SELECT` -> `IN_GAME` transition (T-17), replacing T-14's
 * `startOneVOneGame` now that the FIFA screen exists for players to pick
 * sides. Requires every seat to hold a team (an "Unassigned" straggler left
 * on the strip can't sensibly be "ready" to play, so `canStartGame`'s own
 * "unassigned seats don't count toward either side" — correct for its
 * narrower job of just validating the two counts — isn't sufficient here on
 * its own) *and* `canStartGame`'s four-composition check, *and* every seat
 * `ready` (§5.4: "enabled only when all players are ready and team sizes
 * are valid").
 *
 * `random` is required, not defaulted — rule 1's "no hidden nondeterminism
 * inside a shared function" applies just as much to `Math.random()` as to
 * `Date.now()`, so the caller (`RoomDO`) must supply it explicitly, same as
 * `now` everywhere else. When `settings.randomizeColors` is on, §4.2's "the
 * server flips a coin at game start" is implemented as swapping every seat's
 * WHITE/BLACK label — the FIFA panels already *are* literal colors in this
 * data model (no abstract Team 1/Team 2), so "randomize colors" here means
 * the colors you picked on the panel aren't necessarily the colors you play.
 */
export function startGameFromTeamSelect(
  room: Room,
  actorSeatId: SeatId,
  random: () => number,
): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase !== 'TEAM_SELECT') return fail('INVALID_PHASE');
  if (room.seats.some((s) => s.team === null) || !canStartGame(room.seats)) return fail('TEAM_SIZE_INVALID');
  if (!room.seats.every((s) => s.ready)) return fail('NOT_ALL_READY');

  const flipTeam = (team: Team | null): Team | null => (team === 'WHITE' ? 'BLACK' : team === 'BLACK' ? 'WHITE' : team);
  const flipColors = room.settings.randomizeColors && random() < 0.5;
  const seats = flipColors ? room.seats.map((s) => ({ ...s, team: flipTeam(s.team) })) : room.seats;

  return ok({
    ...room,
    phase: 'IN_GAME',
    seats,
    game: buildInitialGameState(room.settings.timeControl),
  });
}

/**
 * Host-only "Randomize teams" (§5.4) — distinct from `settings.randomizeColors`
 * above: this reshuffles *who* is on which team, not which team plays which
 * color. `random` is required, not defaulted, for the same reason as above.
 * A Fisher-Yates shuffle of the seats, then alternating WHITE/BLACK by
 * shuffled position, guarantees an always-valid, maximally even split for
 * any seat count from 2 to 4.
 */
export function randomizeTeams(room: Room, actorSeatId: SeatId, random: () => number): RoomEngineResult<Room> {
  const actor = room.seats.find((s) => s.seatId === actorSeatId);
  if (!actor) return fail('SEAT_NOT_FOUND');
  if (!actor.isHost) return fail('NOT_HOST');
  if (room.phase !== 'TEAM_SELECT') return fail('INVALID_PHASE');

  const shuffled = [...room.seats];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
  }
  const teamBySeatId = new Map<SeatId, Team>(shuffled.map((s, i) => [s.seatId, i % 2 === 0 ? 'WHITE' : 'BLACK']));

  return ok({ ...room, seats: room.seats.map((s) => ({ ...s, team: teamBySeatId.get(s.seatId)! })) });
}

function findChatSender(
  room: Room,
  seatId: SeatId,
): { publicId: string; username: string; team: Team | null; isSpectator: boolean } | undefined {
  const seat = room.seats.find((s) => s.seatId === seatId);
  if (seat) return { publicId: seat.publicId, username: seat.username, team: seat.team, isSpectator: false };

  const spectator = room.spectators.find((s) => s.seatId === seatId);
  if (spectator) return { publicId: spectator.publicId, username: spectator.username, team: null, isSpectator: true };

  return undefined;
}

/**
 * §5.8/§7 `chat`: `TEAM` reaches your teammate only, and only while you're on
 * a 2-player team during `IN_GAME`; `ALL` reaches every player and spectator
 * in any phase. `text` is already trimmed and length-capped by the wire
 * schema (`chatMessageInputSchema`) before it reaches here, same as
 * `propose`'s square/promotion validation living at the protocol layer.
 *
 * A spectator (or a seat with no team, or a solo team, or outside
 * `IN_GAME`) requesting `TEAM` is rejected with `TEAM_CHAT_UNAVAILABLE`
 * rather than silently rerouted to `ALL` — the client's channel selector
 * should never have offered it, so a request reaching here regardless is
 * either a bug or a forged message, and §7's own wire-table note ("TEAM
 * rejected for spectators and solo teams") reads as a hard rejection, not a
 * fallback.
 *
 * Rate-limited to `CHAT_RATE_LIMIT_COUNT` messages per
 * `CHAT_RATE_LIMIT_WINDOW_MS`, counted against the sender's own messages
 * still in the retained history — the only per-sender timing state this
 * module has, since `Room` carries no separate rate-limit ledger.
 */
export function sendChatMessage(
  room: Room,
  seatId: SeatId,
  text: string,
  channel: ChatChannel,
  now: number,
): RoomEngineResult<Room> {
  const sender = findChatSender(room, seatId);
  if (!sender) return fail('SEAT_NOT_FOUND');

  if (channel === 'TEAM') {
    const teamSize = sender.team ? room.seats.filter((s) => s.team === sender.team).length : 0;
    if (sender.isSpectator || !sender.team || teamSize < 2 || room.phase !== 'IN_GAME') {
      return fail('TEAM_CHAT_UNAVAILABLE');
    }
  }

  const recentCount = room.chat.filter(
    (m) => m.from === sender.publicId && now - m.at < CHAT_RATE_LIMIT_WINDOW_MS,
  ).length;
  if (recentCount >= CHAT_RATE_LIMIT_COUNT) return fail('RATE_LIMITED');

  const message: ChatMessage = {
    id: `c${room.chat.length + 1}`,
    from: sender.publicId,
    fromName: sender.username,
    channel,
    team: channel === 'TEAM' ? sender.team : null,
    isSpectator: sender.isSpectator,
    text,
    at: now,
  };

  return ok({ ...room, chat: [...room.chat, message].slice(-CHAT_HISTORY_LIMIT) });
}
